name: agrosync
description: AgroSync
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  cloud_firestore: ^5.5.4
  firebase_storage: ^12.4.6
  firebase_data_connect: ^0.1.4
  provider: ^6.1.2
  intl: ^0.19.0
  http: ^1.2.2
  sqflite: ^2.0.0+4
  connectivity_plus: ^6.0.3
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.4
  flutter_masked_text2: ^0.9.1
  mask_text_input_formatter: ^2.7.0
  fl_chart: ^0.66.0
  geolocator: ^11.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  pdf: ^3.10.8
  syncfusion_flutter_pdf: ^25.1.39
  #printing: ^5.12
  #share_extend: ^2.0.0
  #path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#388E3C"
  image: assets/logo/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center