name: agrosync
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  firebase_core: ^3.8.0
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_data_connect: any
  provider: ^6.1.2
  intl: ^0.20.2
  http: ^1.2.2
  sqflite: ^2.0.0+4
  connectivity_plus: any
  uuid: ^4.5.1
  hive: any
  hive_flutter: ^1.1.0
  fluttertoast: any
  flutter_masked_text2: any  
  mask_text_input_formatter: ^2.7.0

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/